name: dataanalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - colorama
  - git
  - gitdb
  - gitpython
  - h5py
  - jupyter
  - jupyterlab
  - jupyterlab-git
  - matplotlib
  - numpy
  - nodejs
  - pandas
  - pip
  - pyarrow==1.0.1
  - pytables
  - pyyaml
  - r-arrow==1.0.1
  - r-cairo
  - r-caret
  - r-e1071
  - r-dbi
  - r-hdf5r
  - r-irkernel
  - r-pryr
  - r-randomforest
  - r-recommended
  - r-rsqlite
  - r-svglite
  - r-tidyverse
  - r-vctrs
  - scipy
  - scikit-learn
  - seaborn
  - six
  - smmap
  - sphinx
  - sphinx_rtd_theme
  - sqlalchemy
  - xlrd
  - pip:
    - sphinx-tabs
    - sphinx_rtd_theme_ext_color_contrast
    - https://github.com/coderefinery/sphinx-lesson/archive/master.zip
